ControleContatos/Models/ContatoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControleContatos.Models
{
    public class ContatoModel
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string celular { get; set; }
    }
}

ControleContatos/Models/ErrorViewModel.cs
using System;

namespace ControleContatos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleContatos/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControleContatos.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult ApagarConfirmacao()
        {
            return View();
        }
    }
}

ControleContatos/Controllers/HomeController.cs
using ControleContatos.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ControleContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControleContatos/Views/Contato/ApagarConfirmacao.cshtml
@{
    ViewData["Title"] = "Confirmação de pagar contato";
}

<div class="text-center">

    <h3 class="display-4">Realmente deseja apagar o contato (Thayanne Melo) ?</h3>

</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Contato" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Contato" asp-action="Apagar">Confirmar exclusão</a>

ControleContatos/Views/Contato/Criar.cshtml
@{
    ViewData["Title"] = "Criar Contatos";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Contato</h1>

</div>

<form>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digíte o nome do contato">
    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="email" class="form-control" placeholder="Digíte o e-mail do contato">
    </div>

    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" class="form-control" placeholder="Digíte o celular do contato">
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary d-block btn-block" asp-controller="Contato" Asp-Action="Index" role="button">Voltar</a>
</form>

ControleContatos/Views/Contato/Editar.cshtml
@{
    ViewData["Title"] = "Editar Contatos";
}

<div class="text-center">

    <h1 class="display-4">Editar Contato</h1>

</div>

<form>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digíte o nome do contato">
    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="email" class="form-control" placeholder="Digíte o e-mail do contato">
    </div>

    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" class="form-control" placeholder="Digíte o celular do contato">
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary d-block btn-block" asp-controller="Contato" Asp-Action="Index" role="button">Voltar</a>
</form>

ControleContatos/Views/Contato/Index.cshtml
@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-around-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar novo contato</a>
    </div>

    <br />

    <h1 class="display-4">Listagem de Contatos</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Celular</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto@gmail.com</td>
                <td>11 4402-8922</td>
                <td>

                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>Thornton@gmail.com</td>
                <td>11 4402-8922</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfimacao">Apagar</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>

</div>

ControleContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
   <p>Sistema de controle de contatos</p>
</div>

ControleContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Contatos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Controle de Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>